# Generated by Django 5.2.5 on 2025-08-15 04:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=20, unique=True, verbose_name='CIN')),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_credit', models.CharField(choices=[('divise', 'Crédit divisé en plusieurs parties'), ('unique', 'Crédit unique avec date ou durée')], max_length=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('duree_jours', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('duree_semaines', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(520)])),
                ('duree_mois', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_geres', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='gestion_credits.client')),
            ],
            options={
                'verbose_name': 'Crédit',
                'verbose_name_plural': 'Crédits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_partie', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_echeance', models.DateField()),
                ('date_rappel', models.DateField()),
                ('est_especes', models.BooleanField(default=False)),
                ('est_traitee', models.BooleanField(default=False)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='gestion_credits.credit')),
            ],
            options={
                'verbose_name': 'Échéance',
                'verbose_name_plural': 'Échéances',
                'ordering': ['date_echeance'],
                'unique_together': {('credit', 'numero_partie')},
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=50)),
                ('banque', models.CharField(max_length=100)),
                ('date_emission', models.DateField()),
                ('date_encaissement', models.DateField(blank=True, null=True)),
                ('est_encaisse', models.BooleanField(default=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('echeance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheque', to='gestion_credits.echeance')),
            ],
            options={
                'verbose_name': 'Chèque',
                'verbose_name_plural': 'Chèques',
                'ordering': ['date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('echeance', 'Échéance de paiement'), ('rappel', 'Rappel de paiement'), ('cheque_garantie', 'Chèque de garantie à échéance'), ('retard', 'Paiement en retard')], max_length=20)),
                ('message', models.TextField()),
                ('date_alerte', models.DateField()),
                ('date_rappel', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traitee', 'Traitée'), ('reporter', 'Reportée')], default='en_attente', max_length=15)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_traitement', models.TextField(blank=True, null=True)),
                ('date_report', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_assignees', to=settings.AUTH_USER_MODEL)),
                ('echeance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='gestion_credits.echeance')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-date_alerte'],
            },
        ),
        migrations.CreateModel(
            name='ReportEcheance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_date', models.DateField()),
                ('nouvelle_date', models.DateField()),
                ('raison', models.TextField()),
                ('date_report', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_crees', to=settings.AUTH_USER_MODEL)),
                ('echeance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='gestion_credits.echeance')),
            ],
            options={
                'verbose_name': "Report d'échéance",
                'verbose_name_plural': "Reports d'échéances",
                'ordering': ['-date_report'],
            },
        ),
    ]
