# Generated by Django 5.2.5 on 2025-08-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_credits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='est_encaisse',
        ),
        migrations.AddField(
            model_name='cheque',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='date_reglement_prevu',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue pour règlement'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='remarques',
            field=models.TextField(blank=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='statut',
            field=models.CharField(choices=[('garantie', 'Chèque de Garantie'), ('encaisser', 'À Encaisser'), ('encaisse', 'Encaissé'), ('reporte', 'Reporté'), ('annule', 'Annulé')], default='garantie', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='banque',
            field=models.CharField(max_length=100, verbose_name='Banque émettrice'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='date_emission',
            field=models.DateField(verbose_name="Date d'émission"),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='date_encaissement',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'encaissement"),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='numero_cheque',
            field=models.CharField(max_length=50, verbose_name='Numéro de référence'),
        ),
    ]
