# Generated by Django 5.2.5 on 2025-08-24 17:02

from django.db import migrations, models
import uuid


def generate_unique_police_numbers(apps, schema_editor):
    """Générer des numéros de police uniques pour les crédits existants"""
    Credit = apps.get_model('gestion_credits', 'Credit')
    
    for credit in Credit.objects.all():
        # Générer un numéro de police unique basé sur l'ID et un timestamp
        unique_id = str(uuid.uuid4())[:8].upper()
        credit.numero_police = f"POL-{credit.id:04d}-{unique_id}"
        credit.save()


def reverse_generate_police_numbers(apps, schema_editor):
    """Annuler la génération des numéros de police"""
    Credit = apps.get_model('gestion_credits', 'Credit')
    Credit.objects.all().update(numero_police='0000')


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_credits', '0002_remove_cheque_est_encaisse_cheque_date_modification_and_more'),
    ]

    operations = [
        # 1. Ajouter le champ sans contrainte d'unicité d'abord
        migrations.AddField(
            model_name='credit',
            name='numero_police',
            field=models.CharField(
                default='0000',
                max_length=100,
                verbose_name='Numéro de police',
                help_text="Numéro de police unique attribué par l'agent Sanlam"
            ),
        ),
        
        # 2. Générer des numéros uniques pour les crédits existants
        migrations.RunPython(
            generate_unique_police_numbers,
            reverse_generate_police_numbers
        ),
        
        # 3. Maintenant ajouter la contrainte d'unicité
        migrations.AlterField(
            model_name='credit',
            name='numero_police',
            field=models.CharField(
                max_length=100,
                unique=True,
                verbose_name='Numéro de police',
                help_text="Numéro de police unique attribué par l'agent Sanlam"
            ),
        ),
    ]
