# Generated by Django 5.2.5 on 2025-08-24 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_credits', '0003_credit_numero_police_custom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='numero_police',
            field=models.CharField(default='0000', help_text="Numéro de police unique attribué par l'agent Sanlam", max_length=100, unique=True, verbose_name='Numéro de police'),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('credit_creation', 'Création de crédit'), ('credit_modification', 'Modification de crédit'), ('credit_suppression', 'Suppression de crédit'), ('credit_validation', 'Validation de crédit'), ('echeance_creation', "Création d'échéance"), ('echeance_paiement', "Paiement d'échéance"), ('echeance_report', "Report d'échéance"), ('echeance_annulation', "Annulation d'échéance"), ('cheque_encaissement', 'Encaissement de chèque'), ('cheque_report', 'Report de chèque'), ('cheque_annulation', 'Annulation de chèque'), ('alerte_creation', "Création d'alerte"), ('alerte_traitement', "Traitement d'alerte"), ('alerte_rappel', 'Envoi de rappel'), ('client_creation', 'Création de client'), ('client_modification', 'Modification de client'), ('client_contact', 'Contact client'), ('connexion', 'Connexion agent'), ('deconnexion', 'Déconnexion agent'), ('export_donnees', 'Export de données'), ('import_donnees', 'Import de données')], max_length=50, verbose_name="Type d'action")),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec'), ('en_cours', 'En cours'), ('annule', 'Annulé'), ('en_attente', 'En attente')], default='succes', max_length=20, verbose_name='Statut')),
                ('donnees_avant', models.JSONField(blank=True, null=True, verbose_name='Données avant modification')),
                ('donnees_apres', models.JSONField(blank=True, null=True, verbose_name='Données après modification')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date et heure de l'action")),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Navigateur/Appareil')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de session')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques additionnelles')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Agent responsable')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_historique', to='gestion_credits.client', verbose_name='Client concerné')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_historique', to='gestion_credits.credit', verbose_name='Crédit concerné')),
                ('echeance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_historique', to='gestion_credits.echeance', verbose_name='Échéance concernée')),
            ],
            options={
                'verbose_name': "Log d'action",
                'verbose_name_plural': "Logs d'actions",
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['date_action'], name='gestion_cre_date_ac_93b31d_idx'), models.Index(fields=['type_action'], name='gestion_cre_type_ac_041863_idx'), models.Index(fields=['agent'], name='gestion_cre_agent_i_922971_idx'), models.Index(fields=['client'], name='gestion_cre_client__e2d12a_idx'), models.Index(fields=['credit'], name='gestion_cre_credit__0edc70_idx')],
            },
        ),
    ]
