# Generated by Django 5.2.5 on 2025-08-25 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_credits', '0004_alter_credit_numero_police_actionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ChequeGarantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Numéro de chèque')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banque', models.CharField(max_length=100, verbose_name='Banque émettrice')),
                ('date_emission', models.DateField(verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques_garantie', to='gestion_credits.credit')),
            ],
            options={
                'verbose_name': 'Chèque de garantie',
                'verbose_name_plural': 'Chèques de garantie',
                'ordering': ['date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_reglement', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement')], max_length=20)),
                ('statut', models.CharField(blank=True, choices=[('verse', 'Versé'), ('non_verse', 'Non versé')], max_length=20, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements_crees', to=settings.AUTH_USER_MODEL)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='gestion_credits.credit')),
            ],
            options={
                'verbose_name': 'Règlement',
                'verbose_name_plural': 'Règlements',
                'ordering': ['-date_reglement'],
            },
        ),
    ]
