# Generated by Django 5.2.5 on 2025-08-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_credits', '0005_credit_reste_a_payer_chequegarantie_reglement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='echeance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='gestion_credits.echeance'),
        ),
    ]
